### ISSUE TITLE
Apple Siliconに対応する

### ISSUE THREAD

**Issue by ci7lus** [ci7lus/MirakTest#41]
素のVLCで動作するのは確認できたので各種対応する

VLCをビルドする: https://github.com/vivid-lapin/vlc-miraktest/tree/aarch64

**Comment by ci7lus** [comment]
https://github.com/ci7lus/MirakTest/commit/55b31359cc17751b9861c53d19c286c7b1f35236 ビルドディレクトリがmac-arm64になるので対応

**Comment by ci7lus** [comment]
ユニバーサルビルドは難しそう

```
/Users/user/works/mirakt-universal
› node index.mjs
{
  uniqueToX64: [
    'Contents/Frameworks/vlc/plugins/libbluray-awt-j2se-1.3.0.jar',
    'Contents/Frameworks/vlc/plugins/libbluray-j2se-1.3.0.jar',
    'Contents/Frameworks/vlc/plugins/libi420_rgb_mmx_plugin.dylib',
    'Contents/Frameworks/vlc/plugins/libi420_rgb_sse2_plugin.dylib',
    'Contents/Frameworks/vlc/plugins/libi420_yuy2_mmx_plugin.dylib',
    'Contents/Frameworks/vlc/plugins/libi420_yuy2_sse2_plugin.dylib',
    'Contents/Frameworks/vlc/plugins/libi422_yuy2_mmx_plugin.dylib',
    'Contents/Frameworks/vlc/plugins/libi422_yuy2_sse2_plugin.dylib',
    'Contents/Frameworks/vlc/plugins/plugins.dat'
  ],
  uniqueToArm64: [ 'Contents/Frameworks/vlc/plugins/libgme_plugin.dylib' ]
}
/Users/user/works/mirakt-universal/node_modules/@electron/universal/dist/cjs/index.js:77
            throw new Error('While trying to merge mach-o files across your apps we found a mismatch, the number of mach-o files is not the same between the arm64 and x64 builds');
                  ^

Error: While trying to merge mach-o files across your apps we found a mismatch, the number of mach-o files is not the same between the arm64 and x64 builds
    at exports.makeUniversalApp (/Users/user/works/mirakt-universal/node_modules/@electron/universal/dist/cjs/index.js:77:19)
    at async file:///Users/user/works/mirakt-universal/index.mjs:3:1
```

`https://github.com/electron/universal/issues/36`

**Comment by ci7lus** [comment]
リリースに必要な作業は終わった、CIにはまだaarch64ランタイムは存在しないんので、次リリース時には手元ビルドしたものを追加するようにしてクローズ

**Comment by kilinbox** [comment]
お疲れ様です。
v2.0.0-beta.4のaarch64を早速ダウンロードしたのですがエラーが出て起動できません。
x86_64版は問題ありません。
憶測ですが、ビルド方法が違っておそらく署名あたりが原因じゃないのかなと思っています。
<img width="260" alt="Screen Shot 2022-02-07 at 21 34 13" src="https://user-images.githubusercontent.com/17141779/152789009-3605d67f-0540-442b-9cff-b0257584d60f.png">
、

**Comment by ci7lus** [comment]
@kilinbox パック前にcodesignするようにしてみました、リリースのものを差し替えたので確認お願いします〜！
https://github.com/ci7lus/MirakTest/releases/tag/v2.0.0-beta.4

**Comment by kilinbox** [comment]
対応ありがとうござます。
差し替えたものを確認したところ、無事起動できました。

**Comment by ci7lus** [comment]
動作確認〜配布まで完了したのでクローズします、ありがとうございました！
