### ISSUE TITLE
Windows版v2.0.0-RC1にて実行時にfont-listロードエラー

### ISSUE THREAD

**Issue by unyacat** [ci7lus/MirakTest#70]
## 環境
試したバージョン: `MirakTest-2.0.0-rc.1-win`
Windows10 21H2で実行．

## 内容
実行直後

エラー文
```
globalScreenshotAccelerator繧定ｨｭ螳壹＠縺ｾ縺励◆ undefined
莉･荳九・蜷榊燕縺ｫ蜷郁・縺吶ｋ繝励Λ繧ｰ繧､繝ｳ繧堤┌隕悶＠縺ｾ縺・ []
Error: spawn EPERM
    at ChildProcess.spawn (node:internal/child_process:413:11)
    at spawn (node:child_process:709:9)
    at Object.execFile (node:child_process:336:17)
    at t.<computed> [as execFile] (node:electron/js2c/asar_bundle:5:2208)
    at exec (node:child_process:234:25)
    at node:electron/js2c/asar_bundle:5:12704
    at C:\Users\unyacat\Downloads\MirakTest-2.0.0-rc.1-win\resources\app.asar\node_modules\font-list\libs\win32\getByPowerShell.js:33:3
    at new Promise (<anonymous>)
    at module.exports (C:\Users\unyacat\Downloads\MirakTest-2.0.0-rc.1-win\resources\app.asar\node_modules\font-list\libs\win32\getByPowerShell.js:30:24)
    at module.exports (C:\Users\unyacat\Downloads\MirakTest-2.0.0-rc.1-win\resources\app.asar\node_modules\font-list\libs\win32\index.js:25:21) {
  errno: -4048,
  code: 'EPERM',
  syscall: 'spawn'
}
```

**Comment by ci7lus** [comment]
これちゃんとtry-catchしててエラーレベルが高かっただけだったのでwarnに落としました

**Comment by unyacat** [comment]
🙆👌
